###
POST http://localhost:3005/api/signup
Content-Type: application/json

{
    "user_id": "generated-uuid-v4",
    "first_name": "John",
    "last_name": "Doe",
    "username": "johndoe",
    "email": "john.doe@example.com",
    "password_hash": "hashedpasswordvalue",
    "user_role": "user",
    "user_password": "securepassword123",
    "created_at": "2024-06-01T12:00",
    "updated_at": "2024-06-01T12:00"
}
